---
- hosts: localhost
  connection: local
  tasks:

    - name: Link .vimrc
      ansible.builtin.file:
        src: '{{ ansible_env.PWD }}/vimrc'
        dest: '{{ ansible_env.HOME }}/.vimrc'
        state: link

    - name: Create ~/.vim/autoload (for vim-plug)
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.vim/autoload'
        state: directory

    - name: Install vim-plug
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: '{{ ansible_env.HOME }}/.vim/autoload/plug.vim'
        creates: '{{ ansible_env.HOME }}/.vim/autoload/plug.vim'
      notify: vim_PlugInstall


  handlers:
    - name: vim_PlugInstall
      ansible.builtin.shell:
        cmd: 'vim -u NORC -c"sil! source ~/.vimrc" -c"PlugInstall --sync" +qa'

