---
- hosts: localhost
  connection: local

  vars:
    - HOME: '{{ ansible_env.HOME }}'
    - PWD: '{{ ansible_env.PWD }}'

  roles:
    - git

  tasks:
    - name: Link .vimrc
      ansible.builtin.file:
        src: '{{ PWD }}/vimrc'
        dest: '{{ HOME }}/.vimrc'
        state: link

    - name: Create ~/.vim/autoload (for vim-plug)
      ansible.builtin.file:
        path: '{{ HOME }}/.vim/autoload'
        state: directory

    - name: Install vim-plug
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: '{{ HOME }}/.vim/autoload/plug.vim'
        creates: '{{ HOME }}/.vim/autoload/plug.vim'
      notify: vim_PlugInstall


  handlers:
    - name: vim_PlugInstall
      ansible.builtin.shell:
        cmd: 'vim -u NORC -c"sil! source ~/.vimrc" -c"PlugInstall --sync" +qa'
...
