---
- name: 'zsh : Ensure XDG directories'
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ XDG_CACHE_HOME }}/zsh'
    - '{{ XDG_CONFIG_HOME }}/zsh'
    - '{{ XDG_STATE_HOME }}/zsh'

- name: 'zsh : Link configuration files'
  ansible.builtin.file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { src: '{{ PWD }}/zshenv', dest: '{{ HOME }}/.zshenv' }
    - { src: '{{ PWD }}/zshrc', dest: '{{ XDG_CONFIG_HOME }}/zsh/.zshrc' }

- name: 'zsh : Set as default shell'
  ansible.builtin.shell:
    cmd: 'chsh -s $(which zsh) {{ ansible_env.USER }}'
  become: yes
  when: ansible_user_shell | regex_search('zsh') == none
...
