---
- name: 'ruby : Clone chruby'
  ansible.builtin.git:
    repo: 'https://github.com/postmodern/chruby'
    dest: '{{ PWD }}/../chruby'
    version: 'v0.3.9'
    depth: 1
  notify: 'ruby : Install chruby'

- name: 'ruby : Clone ruby-install'
  ansible.builtin.git:
    repo: 'https://github.com/postmodern/ruby-install'
    dest: '{{ PWD }}/../ruby-install'
    version: 'v0.8.3'
    depth: 1
  notify: 'ruby : Install ruby-install'
...
